#!/usr/bin/env python3

# The sequence of triangle numbers is generated by adding the natural numbers.
# What is the value of the first triangle number to have over five hundred divisors?

import math
from math import sqrt

triangle = 1
i = 1

while True:
    i += 1
    triangle += i
    d = 1
    sq = sqrt(triangle)
    count = 0
    while d <= sq:
        if (triangle % d == 0) & (d < sq):
            count += 2
        if (triangle % d == 0) & (d == sq):
            count += 1
        d += 1
    # print triangle, count
    if count > 500:
        print(triangle, count)
        break
